using System.Collections;
using System.Linq;
using System.Collections.Generic;
using UnityEngine;

public class DiceTests : MonoBehaviour
{
    // Start is called before the first frame update
    void Start()
    {
        /*
        Model2.Space[] spaces = new Model2.Space[40];
        spaces[0] = new Model2.Space.Go(1,"GO",200);
        int[] rents = {2,10,30,90,160,250};
        spaces[1] = new Model2.Space.Property(2,"THE OLD CREEK",60,Group.BROWN,rents,50,250);
        spaces[2] = new Model2.Space.PotLuck(3,"POT LUCK");
        int[] rents2 = {4,20,60,180,320,450};
        spaces[3] = new Model2.Space.Property(4,"GANGSTER PARADISE",60,Group.BROWN,rents2,50,250);
        spaces[4] = new Model2.Space.Tax(5,"INCOME TAX",100);
        int[] srents = {25,50,100,200};
        spaces[5] = new Model2.Space.Station(6,"BRIGHTON STATION",200,srents);
        int[] rents4 = {6,30,90,270,400,550};
        spaces[6] = new Model2.Space.Property(7,"THE ANGELS DELIGHT",60,Group.BLUE,rents4,50,250);
        spaces[7] = new Model2.Space.Chance(8,"OPPORTUNITY KNOCKS");
        spaces[8] = new Model2.Space.Property(9,"POTTER AVENUE",100,Group.BLUE,rents4,50,250);
        int[] rents5 = {8,40,100,300,450,600};
        spaces[9] = new Model2.Space.Property(10,"GRANGER DRIVE",100,Group.BLUE,rents5,50,250);
        spaces[10] =new Model2.Space.VisitJail(11,"JUST VISITING");
        int[] rents6 = {10,50,150,450,625,750};
        spaces[11] =new Model2.Space.Property(12,"SKYWALKER DRIVE",140,Group.PURPLE,rents6,100,500);
        int[] urents = {4,10};
        spaces[12] =new Model2.Space.Utility(13,"TESLA POWER CO",150,urents);
        spaces[13] =new Model2.Space.Property(14,"WOOKIE HOLE",140,Group.PURPLE,rents6,100,500);
        int[] rents8 = {12,60,180,500,700,900};
        spaces[14] =new Model2.Space.Property(15,"REY LANE",160,Group.PURPLE,rents8,100,500);
        spaces[15] =new Model2.Space.Station(16,"HOVE STATION",200,srents);
        int[] rents9 = {14,70,200,550,750,950};
        spaces[16] =new Model2.Space.Property(17,"BISHOP DRIVE",180,Group.ORANGE,rents9,100,500);
        spaces[17] =new Model2.Space.PotLuck(18,"POT LUCK");
        spaces[18] =new Model2.Space.Property(19,"DUNHAM STREET",180,Group.ORANGE,rents9,100,500);
        int[] rents10 = {16,80,220,600,800,1000};
        spaces[19] =new Model2.Space.Property(20,"BROYLES LANE",200,Group.ORANGE,rents10,100,500);
        spaces[20] =new Model2.Space.FreeParking(21,"FREE PARKING");
        int[] rents11 = {18,90,250,700,875,1050};
        spaces[21] =new Model2.Space.Property(22,"YUE FEI SQUARE",220,Group.RED,rents11,150,750);
        spaces[22] =new Model2.Space.Chance(23,"OPPORTUNITY KNOCKS");
        spaces[23] =new Model2.Space.Property(24,"MILAN ROGUE",220,Group.RED,rents11,150,750);
        int[] rents12 = {20,100,300,750,925,1100};
        spaces[24] =new Model2.Space.Property(25,"HAN XIN GARDENS",240,Group.RED,rents12,150,750);
        spaces[25] =new Model2.Space.Station(26,"FALMER STATION",200,srents);
        int[] rents13 = {22,110,330,800,975,1150};
        spaces[26] =new Model2.Space.Property(27,"SHATNER CLOSE",260,Group.YELLOW,rents13,150,750);
        spaces[27] =new Model2.Space.Property(28,"PICARD AVENUE",260,Group.YELLOW,rents13,150,750);
        spaces[28] =new Model2.Space.Utility(29,"EDISON WATER",150,urents);
        spaces[29] =new Model2.Space.Property(30,"CRUSHER CREEK",280,Group.YELLOW,rents13,150,750);
        spaces[30] =new Model2.Space.GoToJail(31,"GO TO JAIL");
        int[] rents14 = {26,130,390,900,1100,1275};
        spaces[31] =new Model2.Space.Property(32,"SIRAT MEWS",300,Group.GREEN,rents14,200,100);
        spaces[32] =new Model2.Space.Property(33,"GENGHIS CRESCENT",300,Group.GREEN,rents14,200,1000);
        spaces[33] =new Model2.Space.PotLuck(34,"POT LUCK");
        int[] rents15 = {28,150,450,1000,1200,1400};
        spaces[34] =new Model2.Space.Property(35,"IBIS CLOSE",320,Group.GREEN,rents15,200,1000);
        spaces[35] =new Model2.Space.Station(36,"PORTSLADE STATION",200,srents);
        spaces[36] =new Model2.Space.Chance(37,"OPPORTUNITY KNOCKS");
        int[] rents16 = {35,175,500,1100,1300,1500};
        spaces[37] =new Model2.Space.Property(38,"JAMES WEBB WAY",350,Group.DEEPBLUE,rents16,200,1000);
        spaces[38] =new Model2.Space.Tax(39,"SUPER TAX",100);
        int[] rents17 = {50,200,600,1400,1700,2000};
        spaces[39] =new Model2.Space.Property(40,"TURING HEIGHTS",400,Group.DEEPBLUE,rents17,200,1000);
        Model2.Board tmp = new Model2.Board(spaces);
        Model2.JSONData.saveBoard(tmp);
        */
        /*
        Model2.CardStack potlucks = new Model2.CardStack();
        Dictionary<string,int> k = new Dictionary<string, int>();
        k.Add("amount",200); 
        potlucks.cards.Add(new Model2.Card("You inherit £200",CardAction.PAYTOPLAYER,k));
        k = new Dictionary<string, int>();
        k.Add("amount",50);
        potlucks.cards.Add(new Model2.Card("You have won 2nd prize in a beauty contest, collect £50",CardAction.PAYTOPLAYER,k));
        k = new Dictionary<string, int>();
        k.Add("position",2);
        potlucks.cards.Add(new Model2.Card("You are up the creek with no paddle - go back to the Old Creek",CardAction.MOVEBACKTO,k));
        k = new Dictionary<string, int>();
        k.Add("amount",20);
        potlucks.cards.Add(new Model2.Card("Student loan refund. Collect £20",CardAction.PAYTOPLAYER,k));
        k = new Dictionary<string, int>();
        k.Add("amount",200);
        potlucks.cards.Add(new Model2.Card("Bank error in your favour. Collect £200",CardAction.PAYTOPLAYER,k));
        k = new Dictionary<string, int>();
        k.Add("amount",100);
        potlucks.cards.Add(new Model2.Card("Pay bill for text books of £100",CardAction.PAYTOBANK,k));
        k = new Dictionary<string, int>();
        k.Add("amount",50);
        potlucks.cards.Add(new Model2.Card("Mega late night taxi bill pay £50",CardAction.PAYTOBANK,k));
        k = new Dictionary<string, int>();
        k.Add("position",1);
        potlucks.cards.Add(new Model2.Card("Advance to go",CardAction.MOVEFORWARDTO,k));
        k = new Dictionary<string, int>();
        k.Add("amount",50);
        potlucks.cards.Add(new Model2.Card("From sale of Bitcoin you get £50",CardAction.PAYTOPLAYER,k));
        potlucks.cards.Add(new Model2.Card("Bitcoin assets fall - pay off Bitcoin short fall",CardAction.PAYTOBANK,k));
        k = new Dictionary<string, int>();
        k.Add("amount",10);
        potlucks.cards.Add(new Model2.Card("Pay a £10 fine or take opportunity knocks",CardAction.PAYORCHANCE,k));
        k = new Dictionary<string, int>();
        k.Add("amount",50);
        potlucks.cards.Add(new Model2.Card("Pay insurance fee of £50",CardAction.PAYTOPARKING,k));
        k = new Dictionary<string, int>();
        k.Add("amount",100);
        potlucks.cards.Add(new Model2.Card("Savings bond matures, collect £100",CardAction.PAYTOPLAYER,k));
        potlucks.cards.Add(new Model2.Card("Go to jail. Do not pass GO, do not collect £200",CardAction.GOTOJAIL));
        k = new Dictionary<string, int>();
        k.Add("amount",25);
        potlucks.cards.Add(new Model2.Card("Received interest on shares of £25",CardAction.PAYTOPLAYER,k));
        k = new Dictionary<string, int>();
        k.Add("amount",10);
        potlucks.cards.Add(new Model2.Card("It's your birthday. Collect £10 from each player",CardAction.BIRTHDAY,k));
        potlucks.cards.Add(new Model2.Card("Get out of jail free",CardAction.OUTOFJAIL));
        Model2.JSONData.saveCardStack(potlucks,"potluck_data.json");
        Model2.CardStack chances = new Model2.CardStack();
        k = new Dictionary<string, int>();
        k.Add("amount",50);
        chances.cards.Add(new Model2.Card("Bank pays you divided of £50",CardAction.PAYTOPLAYER,k));
        k = new Dictionary<string, int>();
        k.Add("amount",100);
        chances.cards.Add(new Model2.Card("You have won a lip sync battle. Collect £100",CardAction.PAYTOPLAYER,k));
        k = new Dictionary<string, int>();
        k.Add("position",40);
        chances.cards.Add(new Model2.Card("Advance to Turing Heights",CardAction.MOVEFORWARDTO,k));
        k = new Dictionary<string, int>();
        k.Add("position",25);
        chances.cards.Add(new Model2.Card("Advance to Han Xin Gardens. If you pass GO, collect £200",CardAction.MOVEFORWARDTO,k));
        k = new Dictionary<string, int>();
        k.Add("amount",15);
        chances.cards.Add(new Model2.Card("Fined £15 for speeding",CardAction.PAYTOPARKING,k));
        k = new Dictionary<string, int>();
        k.Add("amount",150);
        chances.cards.Add(new Model2.Card("Pay university fees of £150",CardAction.PAYTOBANK,k));
        chances.cards.Add(new Model2.Card("Loan matures, collect £150",CardAction.PAYTOPLAYER,k));
        k = new Dictionary<string, int>();
        k.Add("position",16);
        chances.cards.Add(new Model2.Card("Take a trip to Hove station. If you pass GO collect £200",CardAction.MOVEFORWARDTO,k));
        k = new Dictionary<string, int>();
        k.Add("house",40);
        k.Add("hotel",115);
        chances.cards.Add(new Model2.Card("You are assessed for repairs, £40/house, £115/hotel",CardAction.REPAIRS,k));
        k = new Dictionary<string, int>();
        k.Add("position",1);
        chances.cards.Add(new Model2.Card("Advance to go",CardAction.MOVEFORWARDTO,k));
        k = new Dictionary<string, int>();
        k.Add("house",25);
        k.Add("hotel",100);
        chances.cards.Add(new Model2.Card("You are assessed for repairs, £25/house, £100/hotel",CardAction.REPAIRS,k));
        k = new Dictionary<string, int>();
        k.Add("steps",3);
        chances.cards.Add(new Model2.Card("Go back 3 spaces",CardAction.MOVEBACK,k));
        k = new Dictionary<string, int>();
        k.Add("position",12);
        chances.cards.Add(new Model2.Card("Advance to Skywalker Drive. If you pass GO collect £200",CardAction.MOVEFORWARDTO,k));
        chances.cards.Add(new Model2.Card("Go to jail. Do not pass GO, do not collect £200",CardAction.GOTOJAIL));
        k = new Dictionary<string, int>();
        k.Add("amount",30);
        chances.cards.Add(new Model2.Card("Drunk in charge of a hoverboard. Fine £30",CardAction.PAYTOPARKING,k));
        chances.cards.Add(new Model2.Card("Get out of jail free",CardAction.OUTOFJAIL));
        Model2.JSONData.saveCardStack(chances,"opportunity_knocks_data.json");
        */
    }
}
